### PR TITLE
Touch icons and multiple values in rel attribute

### PR DESCRIPTION
**Pull request by gswirski**
This PR stores all icons (favicon + touch icons) in `Icons` array. It also fixes handling of `image_src` on websites like http://stackoverflow.com (note multiple `rel` values).

### CODE REVIEW

**Comment by dyatlov** [comment]
Hey, @gswirski 
current code will set FaviconURL to last found icon.. 
There's no problem with using last icon, but it shouldn't select apple-touch-icon as favicon.. because it's not it :)
Also I guess that `strings.Contains(m["rel"], "icon") || strings.Contains(m["rel"], "image_src")` are weak conditions and should be replacced with a regex because if there would be a ref with content like: `rel="vicont"` then code will be in trouble :) I'd suggest regexes `\bicon\b` and `\bimage_src\b`

**Comment by dyatlov** [comment]
Also, regarding `image_src` - I not agree that it should be `icon`.
That's widely used for page thumbnails: http://stackoverflow.com/questions/19274463/what-is-link-rel-image-src
So it should be used as a failsafe mechanism for obtaining main page image.
Have a look at the source code of this page: http://habrahabr.ru/post/270715/ (sorry for russian)
image_src here is just a main page image.

**Comment by gswirski** [comment]
I should have made the code more obvious - `image_src` is not an icon and `apple-touch-icon` is not a favicon. I totally agree. The `continue` statements prevent exactly these behaviors. I'll update my PR to make it more visible.

The reason why I decided to use the same code path for icons and image_srcs is because some websites (e.g. stackoverflow) reuse the same `link` tag for both.

I like the `\b(icon|image_src)\b` idea.

**Comment by gswirski** [comment]
I've updated my PR. Now the code is more explicit what's going on.

**Comment by gswirski** [comment]
I've updated my PR. The code should be more explicit now.

I renamed `Icons` to `TouchIcons` but kept favicon inside the array. It makes parsing a little simpler (`rel="icon" sizes="HHHxWWW"` is the Android way of doing touch icons), and favicon can be treated as a "last resort" when no other touch icon has been found).

**Comment by dyatlov** [comment]
Cool, thank you! Merging now!

**Pull request merged**
